package com.Models;
// Generated 22 août 2015 10:23:34 by Hibernate Tools 3.2.1.GA



/**
 * Client generated by hbm2java
 */
public class Client  implements java.io.Serializable {


     private Integer id;
     private String nom;
     private String adresse;
     private int solde;

    public Client() {
    }

    public Client(String nom, String adresse, int solde) {
       this.nom = nom;
       this.adresse = adresse;
       this.solde = solde;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getNom() {
        return this.nom;
    }
    
    public void setNom(String nom) {
        this.nom = nom;
    }
    public String getAdresse() {
        return this.adresse;
    }
    
    public void setAdresse(String adresse) {
        this.adresse = adresse;
    }
    public int getSolde() {
        return this.solde;
    }
    
    public void setSolde(int solde) {
        this.solde = solde;
    }




}


