package com.Models;
// Generated 21 juil. 2015 09:50:09 by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;

/**
 * Client generated by hbm2java
 */
public class Client  implements java.io.Serializable {


     private Integer id;
     private String nom;
     private String adresse;
     private BigDecimal solde;

    public Client() {
    }

    public Client(String nom, String adresse, BigDecimal solde) {
       this.nom = nom;
       this.adresse = adresse;
       this.solde = solde;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getNom() {
        return this.nom;
    }
    
    public void setNom(String nom) {
        this.nom = nom;
    }
    public String getAdresse() {
        return this.adresse;
    }
    
    public void setAdresse(String adresse) {
        this.adresse = adresse;
    }
    public BigDecimal getSolde() {
        return this.solde;
    }
    
    public void setSolde(BigDecimal solde) {
        this.solde = solde;
    }




}


